rollback pipeline step zap dast

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -151,46 +151,46 @@ jobs:
           publish_dir: public
           publish_branch: gh-pages
 
-# ==========================================================
-# DAST (ZAP) — JALAN SETELAH SWAGGER SIAP
-# ==========================================================
-  dast:
-    name: ZAP DAST
-    runs-on: ubuntu-latest
-    needs: report   # 🔥 SERIAL, BUKAN PARALEL
+# # ==========================================================
+# # DAST (ZAP) — JALAN SETELAH SWAGGER SIAP
+# # ==========================================================
+#   dast:
+#     name: ZAP DAST
+#     runs-on: ubuntu-latest
+#     needs: report   # 🔥 SERIAL, BUKAN PARALEL
 
-    steps:
-      - uses: actions/checkout@v4
+#     steps:
+#       - uses: actions/checkout@v4
 
-      - name: Start Docker Compose (CI)
-        run: |
-          docker compose -f docker-compose.ci.yml up -d
-          docker compose -f docker-compose.ci.yml ps
+#       - name: Start Docker Compose (CI)
+#         run: |
+#           docker compose -f docker-compose.ci.yml up -d
+#           docker compose -f docker-compose.ci.yml ps
 
-      - name: Wait API (Swagger ready)
-        run: |
-          echo "⏳ Waiting for Swagger..."
-          for i in {1..40}; do
-            if curl -s https://adamf0.github.io/UnpakSiamidaV2/swagger/swagger.json | grep -q '"openapi"'; then
-              echo "✅ Swagger is ready"
-              exit 0
-            fi
-            sleep 3
-          done
-          echo "❌ Swagger not ready"
-          exit 1
+#       - name: Wait API (Swagger ready)
+#         run: |
+#           echo "⏳ Waiting for Swagger..."
+#           for i in {1..40}; do
+#             if curl -s https://adamf0.github.io/UnpakSiamidaV2/swagger/swagger.json | grep -q '"openapi"'; then
+#               echo "✅ Swagger is ready"
+#               exit 0
+#             fi
+#             sleep 3
+#           done
+#           echo "❌ Swagger not ready"
+#           exit 1
 
-      - name: ZAP DAST Scan
-        uses: zaproxy/action-api-scan@v0.7.0
-        with:
-          target: https://adamf0.github.io/UnpakSiamidaV2/swagger/swagger.json
-          format: openapi
-          fail_action: false
-          cmd_options: "-a -m 5 -l WARN"
+#       - name: ZAP DAST Scan
+#         uses: zaproxy/action-api-scan@v0.7.0
+#         with:
+#           target: https://adamf0.github.io/UnpakSiamidaV2/swagger/swagger.json
+#           format: openapi
+#           fail_action: false
+#           cmd_options: "-a -m 5 -l WARN"
 
-      - name: Shutdown containers
-        if: always()
-        run: docker compose -f docker-compose.ci.yml down
+#       - name: Shutdown containers
+#         if: always()
+#         run: docker compose -f docker-compose.ci.yml down
 
 # ==========================================================
 # SECRET SCANNING
